import { Router } from 'express';
import { createAsset, createBundle, createExpenseVoucher, createSalesInvoice, createStockDocument, getAssets, getBundles, getDeliveries, getExpenseVouchers, getSalesInvoices, getStockDocuments, recordSalesInvoicePayment, updateAsset, updateBundle, updateDelivery, updateExpenseVoucher, updateSalesInvoice } from '../controllers/operations.controller.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.use(requireAuth);
router.get('/stock-documents', getStockDocuments);
router.post('/stock-documents', createStockDocument);
router.get('/deliveries', getDeliveries);
router.patch('/deliveries/:id', updateDelivery);
router.get('/assets', getAssets);
router.post('/assets', createAsset);
router.put('/assets/:id', updateAsset);
router.get('/bundles', getBundles);
router.post('/bundles', createBundle);
router.put('/bundles/:id', updateBundle);
router.get('/expenses', getExpenseVouchers);
router.post('/expenses', createExpenseVoucher);
router.patch('/expenses/:id', updateExpenseVoucher);
router.get('/invoices', getSalesInvoices);
router.post('/invoices', createSalesInvoice);
router.post('/invoices/:id/payments', recordSalesInvoicePayment);
router.patch('/invoices/:id', updateSalesInvoice);
export default router;
